### ISSUE TITLE
Unable to install pillow using pip

### ISSUE THREAD

**Issue by saisriker** [raymondbutcher/terraform-aws-lambda-builder#13]
Getting error like this:
ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/home/sbx_user1051'
When I use virtual enivornment the package is not getting build with correct directory path

**Comment by raymondbutcher** [comment]
I tried it and it worked. I think what you were missing was the `-t` argument when using pip. The [python tests](https://github.com/raymondbutcher/terraform-aws-lambda-builder/tree/master/tests/python) show how you can use pip.
