### ISSUE TITLE
Can you have this support python 3.8 runtime

### ISSUE THREAD

**Issue by csima** [raymondbutcher/terraform-aws-lambda-builder#6]

**Comment by raymondbutcher** [comment]
This is blocked by https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/80

It could be worked around by zipping up the builder function code and uploading that to S3, but I'd prefer to keep the source code embedded in the CloudFormation template as it's fewer resources to deal with.

All runtimes should work in the `CODEBUILD` build mode, however that's a bit slower than the `LAMBDA` mode.

**Comment by raymondbutcher** [comment]
Good news, they unblocked it so I've added support in fae1ce8234238dfeec4ab2b9c2c574f924c81ec5
