### ISSUE TITLE
random_string causes FILENAME build mode to fail

### ISSUE THREAD

**Issue by ekfastlane** [raymondbutcher/terraform-aws-lambda-builder#7]
Hi,

in main.tf:

```
resource "random_string" "build_id" {
  count = var.enabled && contains(["CODEBUILD", "LAMBDA"], var.build_mode) ? 1 : 0
}

locals {
  key_target_name = "${random_string.build_id[0].result}.zip"
}
```

This code fails with any build modes which are not CODEBUILD or LAMBDA as key_target_name is getting initialised regardless of what build mode is, resulting in the following Terraform error:

```
Error: Invalid index

  on .terraform/modules/get_resume_lambda_function/main.tf line 133, in locals:
 133:   key_target_name = "${random_string.build_id[0].result}.zip"
    |----------------
    | random_string.build_id is empty tuple

The given key does not identify an element in this collection value.
```

As random_string resource is in-memory only, I would suggest a change so it always gets created? Pull request to follow up.

**Comment by raymondbutcher** [comment]
As I said in the PR, I'm pretty sure this has been fixed. Thanks again.
